// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {testpkg} from '../models';
import {context} from '../models';

export function GetJson():Promise<testpkg.TestObj>;

export function GetValue():Promise<string>;

export function Greet(arg1:string):Promise<string>;

export function Startup(arg1:context.Context):Promise<void>;
