// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetJson() {
  return window['go']['testpkg']['Test']['GetJson']();
}

export function GetValue() {
  return window['go']['testpkg']['Test']['GetValue']();
}

export function Greet(arg1) {
  return window['go']['testpkg']['Test']['Greet'](arg1);
}

export function SetValue(arg1) {
  return window['go']['testpkg']['Test']['SetValue'](arg1);
}

export function Startup(arg1) {
  return window['go']['testpkg']['Test']['Startup'](arg1);
}
