// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetJson() {
  return window['go']['main']['Test']['GetJson']();
}

export function GetValue() {
  return window['go']['main']['Test']['GetValue']();
}

export function Greet(arg1) {
  return window['go']['main']['Test']['Greet'](arg1);
}
